import os
import glob
from pathlib import Path

def generate_test_boilerplates(src_dir="src", tests_dir="tests"):
    print("\033[1;33m🛡️ bestAI Guardian: Token-Saving Test Builder\033[0m")
    print("Scanning codebase to generate test boilerplates locally (Zero token cost)...\n")

    if not os.path.exists(src_dir):
        print(f"Directory {src_dir} not found. Skipping auto-test generation.")
        return

    os.makedirs(tests_dir, exist_ok=True)
    generated = 0

    # Scan for Python files (extendable)
    for filepath in glob.glob(f"{src_dir}/**/*.py", recursive=True):
        if "__init__.py" in filepath: continue
        
        path = Path(filepath)
        test_filename = f"test_{path.name}"
        test_filepath = os.path.join(tests_dir, test_filename)

        if not os.path.exists(test_filepath):
            with open(test_filepath, 'w') as f:
                f.write(f'# Auto-generated by bestAI Guardian\n')
                f.write(f'# Target: {filepath}\n')
                f.write(f'import pytest\n\n')
                f.write(f'def test_unimplemented_{path.stem}():\n')
                f.write(f'    """\n    TODO for AI Agent: Implement unit tests for {path.name} based on GPS.json specs.\n    """\n')
                f.write(f'    assert False, "Test not implemented"\n')
            
            print(f"Created boilerplate: {test_filepath}")
            generated += 1

    if generated > 0:
        print(f"\n\033[1;32m✅ Saved significant tokens!\033[0m")
        print(f"Generated {generated} test stubs. Command your agent to 'Fill them in'.")
    else:
        print("✅ Codebase covered. Guardian standing down.")

if __name__ == "__main__":
    # Default search in local dir if /src is missing, for flexibility
    search_dir = "src" if os.path.exists("src") else "."
    generate_test_boilerplates(src_dir=search_dir)
