#!/bin/bash
# hooks/sync-state.sh — Stop hook
# Minimal runtime sync: session-log append + LAST SESSION DELTA refresh.

set -euo pipefail

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"
PROJECT_KEY=$(echo "$PROJECT_DIR" | tr '/' '-')
MEMORY_DIR="${SYNC_STATE_MEMORY_DIR:-$HOME/.claude/projects/$PROJECT_KEY/memory}"
SESSION_LOG="$MEMORY_DIR/session-log.md"
STATE_FILE="${SYNC_STATE_STATE_FILE:-$PROJECT_DIR/.claude/state-of-system-now.md}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

mkdir -p "$MEMORY_DIR"

INPUT=$(cat)
if command -v jq >/dev/null 2>&1; then
    RESPONSE_LINE=$(echo "$INPUT" | jq -r '.response.output_text // .assistant_message // .output // empty' 2>/dev/null | head -n 1)
else
    RESPONSE_LINE=""
fi

CHANGED_FILES=""
if [ -d "$PROJECT_DIR/.git" ]; then
    CHANGED_FILES=$(git -C "$PROJECT_DIR" status --porcelain 2>/dev/null | awk '{print $2}' | head -n 10 || true)
fi

if [ -z "$CHANGED_FILES" ]; then
    CHANGED_FILES="(no working tree changes detected)"
fi

if [ ! -f "$SESSION_LOG" ]; then
    cat > "$SESSION_LOG" <<'LOG_HEADER'
# Session Log

Chronological sync entries generated by hooks/sync-state.sh.
LOG_HEADER
fi

{
    echo ""
    echo "## $TIMESTAMP"
    echo "- changed_files:"
    echo "$CHANGED_FILES" | sed 's/^/  - /'
    if [ -n "$RESPONSE_LINE" ]; then
        echo "- response_summary: ${RESPONSE_LINE:0:180}"
    fi
} >> "$SESSION_LOG"

if [ -f "$STATE_FILE" ]; then
    TMP_STATE=$(mktemp)
    DELTA_TMP=$(mktemp)

    {
        echo "- updated_utc: $TIMESTAMP"
        echo "- changed_files:"
        echo "$CHANGED_FILES" | sed 's/^/  - /'
        if [ -n "$RESPONSE_LINE" ]; then
            echo "- response_summary: ${RESPONSE_LINE:0:180}"
        fi
    } > "$DELTA_TMP"

    awk '
    BEGIN {skip=0}
    /^## LAST SESSION DELTA \(auto\)/ {skip=1; next}
    skip && /^## / {skip=0}
    !skip {print}
    ' "$STATE_FILE" > "$TMP_STATE"

    {
        echo ""
        echo "## LAST SESSION DELTA (auto)"
        cat "$DELTA_TMP"
    } >> "$TMP_STATE"

    mv "$TMP_STATE" "$STATE_FILE"
    rm -f "$DELTA_TMP"
fi

exit 0
