#!/bin/bash
# hooks/sync-state.sh — Stop hook
# Minimal runtime sync: session-log append + LAST SESSION DELTA refresh.

set -euo pipefail

# Shared event logging
source "$(dirname "$0")/hook-event.sh" 2>/dev/null || true

BESTAI_DRY_RUN="${BESTAI_DRY_RUN:-0}"

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"
PROJECT_KEY=$(echo "$PROJECT_DIR" | tr '/' '-')
MEMORY_DIR="${SYNC_STATE_MEMORY_DIR:-$HOME/.claude/projects/$PROJECT_KEY/memory}"
SESSION_LOG="$MEMORY_DIR/session-log.md"
STATE_FILE="${SYNC_STATE_STATE_FILE:-$PROJECT_DIR/.claude/state-of-system-now.md}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

mkdir -p "$MEMORY_DIR"

INPUT=$(cat)
if command -v jq >/dev/null 2>&1; then
    RESPONSE_LINE=$(echo "$INPUT" | jq -r '.response.output_text // .assistant_message // .output // empty' 2>/dev/null | head -n 1)
else
    RESPONSE_LINE=""
fi

CHANGED_FILES=""
if [ -d "$PROJECT_DIR/.git" ]; then
    CHANGED_FILES=$(git -C "$PROJECT_DIR" status --porcelain 2>/dev/null | awk '{print $2}' | head -n 10 || true)
fi

if [ -z "$CHANGED_FILES" ]; then
    CHANGED_FILES="(no working tree changes detected)"
fi

if [ "$BESTAI_DRY_RUN" = "1" ]; then
    echo "[DRY-RUN] Would sync state: session-log + state delta" >&2
    emit_event "sync-state" "DRY_RUN" "{}" 2>/dev/null || true
    exit 0
fi

if [ ! -f "$SESSION_LOG" ]; then
    cat > "$SESSION_LOG" <<'LOG_HEADER'
# Session Log

Chronological sync entries generated by hooks/sync-state.sh.
LOG_HEADER
fi

{
    echo ""
    echo "## $TIMESTAMP"
    echo "- changed_files:"
    echo "$CHANGED_FILES" | sed 's/^/  - /'
    if [ -n "$RESPONSE_LINE" ]; then
        echo "- response_summary: ${RESPONSE_LINE:0:180}"
    fi
} >> "$SESSION_LOG"

# Rotate session-log: keep last 50 entries, archive older ones.
MAX_ENTRIES=${SYNC_STATE_MAX_LOG_ENTRIES:-50}
ENTRY_COUNT=$(grep -c '^## ' "$SESSION_LOG" 2>/dev/null || echo 0)
if [ "$ENTRY_COUNT" -gt "$MAX_ENTRIES" ]; then
    ARCHIVE_FILE="$MEMORY_DIR/session-log-archive.md"
    KEEP_FROM=$((ENTRY_COUNT - MAX_ENTRIES + 1))

    if [ ! -f "$ARCHIVE_FILE" ]; then
        echo "# Session Log Archive" > "$ARCHIVE_FILE"
        echo "" >> "$ARCHIVE_FILE"
        echo "Rotated entries from session-log.md." >> "$ARCHIVE_FILE"
    fi

    # Extract entries to archive (everything before the Nth-from-last ## header)
    KEEP_LINE=$(grep -n '^## ' "$SESSION_LOG" | sed -n "${KEEP_FROM}p" | cut -d: -f1)
    if [ -n "$KEEP_LINE" ] && [ "$KEEP_LINE" -gt 1 ]; then
        head -n "$((KEEP_LINE - 1))" "$SESSION_LOG" \
            | grep -v '^# Session Log' \
            | grep -v '^Chronological sync' \
            | sed '/^$/N;/^\n$/d' \
            >> "$ARCHIVE_FILE"

        TMP_LOG=$(mktemp)
        {
            echo "# Session Log"
            echo ""
            echo "Chronological sync entries generated by hooks/sync-state.sh."
            tail -n "+$KEEP_LINE" "$SESSION_LOG"
        } > "$TMP_LOG"
        mv "$TMP_LOG" "$SESSION_LOG"
    fi
fi

if [ -f "$STATE_FILE" ]; then
    TMP_STATE=$(mktemp)
    DELTA_TMP=$(mktemp)

    {
        echo "- updated_utc: $TIMESTAMP"
        echo "- changed_files:"
        echo "$CHANGED_FILES" | sed 's/^/  - /'
        if [ -n "$RESPONSE_LINE" ]; then
            echo "- response_summary: ${RESPONSE_LINE:0:180}"
        fi
    } > "$DELTA_TMP"

    awk '
    BEGIN {skip=0}
    /^## LAST SESSION DELTA \(auto\)/ {skip=1; next}
    skip && /^## / {skip=0}
    !skip {print}
    ' "$STATE_FILE" > "$TMP_STATE"

    {
        echo ""
        echo "## LAST SESSION DELTA (auto)"
        cat "$DELTA_TMP"
    } >> "$TMP_STATE"

    mv "$TMP_STATE" "$STATE_FILE"
    rm -f "$DELTA_TMP"
fi

emit_event "sync-state" "DONE" "{}" 2>/dev/null || true
exit 0
