#!/bin/bash
# tools/generate-rules.sh
# Generates cross-tool compatibility rules (Cursor, Windsurf, Copilot, Codex)
# Usage: bash tools/generate-rules.sh [project-dir] --format [cursor|windsurf|copilot|codex]

set -euo pipefail

usage() {
    cat <<'EOF'
Usage: bash tools/generate-rules.sh [project-dir] [--format <cursor|windsurf|copilot|codex>]

Examples:
  bash tools/generate-rules.sh . --format codex
  bash tools/generate-rules.sh /path/to/project --format cursor
EOF
}

TARGET="."
FORMAT="cursor"
TARGET_SET=0

while [ "$#" -gt 0 ]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --format)
            [ "$#" -ge 2 ] || { echo "Error: missing value for --format." >&2; exit 1; }
            FORMAT="${2:-}"
            shift 2
            ;;
        --format=*)
            FORMAT="${1#*=}"
            shift
            ;;
        --*)
            echo "Error: unknown option '$1'." >&2
            usage >&2
            exit 1
            ;;
        *)
            if [ "$TARGET_SET" -eq 0 ]; then
                TARGET="$1"
                TARGET_SET=1
            else
                echo "Error: unexpected argument '$1'." >&2
                usage >&2
                exit 1
            fi
            shift
            ;;
    esac
done

case "$FORMAT" in
    cursor|windsurf|copilot|codex) ;;
    *)
        echo "Error: unsupported --format '$FORMAT' (supported: cursor|windsurf|copilot|codex)." >&2
        exit 1
        ;;
esac

if [ ! -d "$TARGET" ]; then
    echo "Error: target directory '$TARGET' does not exist." >&2
    exit 1
fi

if [ ! -f "$TARGET/AGENTS.md" ]; then
    echo "Error: AGENTS.md not found in $TARGET. Cannot generate cross-tool rules." >&2
    exit 1
fi

if [ ! -f "$TARGET/CLAUDE.md" ]; then
    echo "Error: CLAUDE.md not found. Required as base instruction set." >&2
    exit 1
fi

# HEADER GENERATION (Standardized uppercase header)
cat <<EOF
# ==============================================================================
# AUTOGENERATED bestAI RULES FOR: ${FORMAT^^}
# Do not edit this file directly. Edit CLAUDE.md and AGENTS.md instead.
# ==============================================================================

EOF

# For all formats, we merge the general guidelines with the specific project rules
cat "$TARGET/AGENTS.md"
echo ""
echo "--- PROJECT SPECIFIC RULES ---"
echo ""
cat "$TARGET/CLAUDE.md"

if [ "$FORMAT" = "cursor" ]; then
    echo ""
    echo "--- CURSOR SPECIFIC DIRECTIVES ---"
    echo "- Always read .bestai/GPS.json before starting a task to understand your role."
    echo "- When editing files, ensure you respect the frozen files listed in memory/frozen-fragments.md."
    echo "- Do not use sed or awk for complex replacements; use your native file editing capabilities safely."
elif [ "$FORMAT" = "windsurf" ]; then
    echo ""
    echo "--- WINDSURF SPECIFIC DIRECTIVES ---"
    echo "- Execute bash hooks located in .claude/hooks/ manually if the environment does not auto-trigger them."
    echo "- Consult T3-summary.md for a map of the codebase to prevent context overflow."
elif [ "$FORMAT" = "copilot" ]; then
    echo ""
    echo "--- COPILOT SPECIFIC DIRECTIVES ---"
    echo "- Treat AGENTS.md and CLAUDE.md as authoritative policy documents."
    echo "- Respect frozen files and [USER] decisions before code edits."
elif [ "$FORMAT" = "codex" ]; then
    echo ""
    echo "--- CODEX SPECIFIC DIRECTIVES ---"
    echo "- Treat AGENTS.md and CLAUDE.md as highest-priority project constraints."
    echo "- Enforce frozen files and [USER] memory entries before any write or edit."
    echo "- Use project-local scripts for validation (tests, lint, doctor) before finalizing changes."
fi
