#!/bin/bash
# tools/generate-rules.sh
# Generates cross-tool compatibility rules (Cursor, Windsurf, Copilot)
# Usage: bash tools/generate-rules.sh [project-dir] --format [cursor|windsurf|copilot]

set -euo pipefail

TARGET="${1:-.}"
FORMAT="cursor"

while [ "$#" -gt 0 ]; do
    case "$1" in
        --format)
            FORMAT="${2:-}"
            shift 2
            ;;
        *)
            TARGET="$1"
            shift
            ;;
    esac
done

if [ ! -f "$TARGET/AGENTS.md" ]; then
    echo "Error: AGENTS.md not found in $TARGET. Cannot generate cross-tool rules." >&2
    exit 1
fi

if [ ! -f "$TARGET/CLAUDE.md" ]; then
    echo "Error: CLAUDE.md not found. Required as base instruction set." >&2
    exit 1
fi

cat <<EOF
# ==============================================================================
# AUTOGENERATED bestAI RULES FOR: ${FORMAT^^}
# Do not edit this file directly. Edit CLAUDE.md and AGENTS.md instead.
# ==============================================================================

EOF

# For Cursor and Windsurf, we merge the general guidelines with the specific project rules
cat "$TARGET/AGENTS.md"
echo ""
echo "--- PROJECT SPECIFIC RULES ---"
echo ""
cat "$TARGET/CLAUDE.md"

if [ "$FORMAT" = "cursor" ]; then
    echo ""
    echo "--- CURSOR SPECIFIC DIRECTIVES ---"
    echo "- Always read .bestai/GPS.json before starting a task to understand your role."
    echo "- When editing files, ensure you respect the frozen files listed in memory/frozen-fragments.md."
    echo "- Do not use sed or awk for complex replacements; use your native file editing capabilities safely."
elif [ "$FORMAT" = "windsurf" ]; then
    echo ""
    echo "--- WINDSURF SPECIFIC DIRECTIVES ---"
    echo "- Execute bash hooks located in .claude/hooks/ manually if the environment does not auto-trigger them."
    echo "- Consult T3-summary.md for a map of the codebase to prevent context overflow."
fi
