import os
import glob
from pathlib import Path

def generate_test_boilerplates(src_dir="src", tests_dir="tests"):
    print("\033[1;33m🛡️ bestAI Guardian: Token-Saving Test Builder\033[0m")
    print("Scanning codebase to generate test boilerplates locally (Zero token cost)...
")

    if not os.path.exists(src_dir):
        print(f"Directory {src_dir} not found. Skipping auto-test generation.")
        return

    os.makedirs(tests_dir, exist_ok=True)
    generated = 0

    # Look for Python files as an example (can be extended to JS/TS)
    for filepath in glob.glob(f"{src_dir}/**/*.py", recursive=True):
        if "__init__.py" in filepath: continue
        
        path = Path(filepath)
        test_filename = f"test_{path.name}"
        test_filepath = os.path.join(tests_dir, test_filename)

        if not os.path.exists(test_filepath):
            with open(test_filepath, 'w') as f:
                f.write(f'# Auto-generated by bestAI Guardian
')
                f.write(f'# Target: {filepath}
')
                f.write(f'import pytest

')
                f.write(f'def test_unimplemented_{path.stem}():
')
                f.write(f'    """
    TODO for AI Agent: Implement unit tests for {path.name} based on GPS.json functionality.
    """
')
                f.write(f'    assert False, "Test not implemented"
')
            
            print(f"Created boilerplate: {test_filepath}")
            generated += 1

    if generated > 0:
        print(f"
\033[1;32m✅ Saved roughly {generated * 1500} tokens!\033[0m")
        print("You can now instruct your agent: 'Fill in the empty tests in the /tests directory.'")
    else:
        print("✅ Codebase is already covered with test files. Guardian standing down.")

if __name__ == "__main__":
    generate_test_boilerplates()
